import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./nextAuthProvider";
import { CmsContextProvider } from "./context/cms";
import { EnvContextProvider } from "./context/env";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <CmsContextProvider>
            <EnvContextProvider>{children}</EnvContextProvider>
          </CmsContextProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
